# Generated by Django 4.2.16 on 2024-10-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompost',
            name='approved_on',
            field=models.BooleanField(default=False),
        ),
    ]
